# Generated by Django 5.1.3 on 2024-11-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecuredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom du Fichier')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Ajout")),
                ('encrypted_key', models.TextField(blank=True, null=True, verbose_name='Clé de Chiffrement')),
            ],
        ),
    ]
