# Generated by Django 5.1.1 on 2024-11-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_temoignage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtest',
            name='lien',
            field=models.EmailField(max_length=50),
        ),
    ]
